-- OpenKraken on Omarchy / Hyprland — optional window rules and autostart.
--
-- Omarchy configures Hyprland in Lua and loads your files after its own
-- defaults, so this belongs in ~/.config/hypr/. Two ways to use it:
--
--   1. Copy the rules you want straight into ~/.config/hypr/hyprland.lua
--      (window rules) and ~/.config/hypr/autostart.lua (the launch line).
--   2. Or drop this whole file in as ~/.config/hypr/openkraken.lua and add
--      `require("hypr.openkraken")` to ~/.config/hypr/hyprland.lua. (Omarchy's
--      Lua path is rooted at ~/.config, which is why its own stock lines read
--      `require("hypr.monitors")` and friends — a bare `require("openkraken")`
--      will not resolve.)
--
-- After editing, validate — Hyprland auto-reloads, but errors are only visible
-- if you look:
--
--     hyprctl reload && hyprctl configerrors
--
-- Nothing here is required: OpenKraken tiles and runs perfectly well with no
-- rules at all. These just make it behave like the control panel it is.

-- --------------------------------------------------------------------------
-- Window rules
-- --------------------------------------------------------------------------
-- The Wayland app_id is "openkraken" (set by the app via setDesktopFileName),
-- so a plain class match is all that is needed — verified with
-- `hyprctl clients -j` on Omarchy 4.0.2, where the window reports
-- class="openkraken", xwayland=false.
--
-- OpenKraken tiles correctly and needs no rule at all. Its Dashboard re-flows
-- the gauge row and the Display checkboxes when the tiler hands it a narrow
-- column, so nothing overflows or clips.
--
-- It did not always: the gauge row was an unwrappable QHBoxLayout with an
-- 830 px floor, and a tiler allocates whatever width it likes regardless of
-- size hints, at which point the row sheared off past the window edge. On
-- v0.4.0 and older, the two rules below are the workaround.
--
-- Uncomment to float and centre it anyway, the way Omarchy treats its own
-- utility windows (see $OMARCHY_PATH/default/hypr/apps/):
-- o.window("^(openkraken)$", { float = true, center = true })
-- o.window("^(openkraken)$", { size = { 920, 740 } })
--
-- Note the app's own setMinimumSize() is a floor Qt clamps to, so a rule
-- narrower than it looks ignored: 640x560 as of v0.4.1, and 920x640 before.

-- Optional extras, commented out — uncomment what you want:
--
-- Keep the gauges readable rather than translucent (Omarchy applies a default
-- opacity to every window; opting out needs the tag removed *and* an override).
-- o.window("^(openkraken)$", { tag = "-default-opacity" })
-- o.window("^(openkraken)$", { opacity = "1 1" })
--
-- Park it on a dedicated workspace instead of wherever it opens.
-- o.window("^(openkraken)$", { workspace = "9" })

-- --------------------------------------------------------------------------
-- Autostart
-- --------------------------------------------------------------------------
-- Only needed if you want CPU/GPU-temp curves, lighting effects, or live LCD
-- sensor screens to come back on their own at login. Liquid-temp curves run
-- inside the cooler's firmware and persist without the app running at all.
--
-- The portable route works on Omarchy and is the one I would pick, because
-- uwsm turns it into a real systemd user unit -- which means journald logs and
-- a way to test it without logging out:
--
--     mkdir -p ~/.config/autostart
--     cp /usr/share/applications/openkraken.desktop ~/.config/autostart/
--     sed -i 's|^Exec=.*|Exec=/usr/bin/openkraken --minimized|' \
--         ~/.config/autostart/openkraken.desktop
--     systemctl --user daemon-reload
--     systemctl --user start app-openkraken@autostart.service   # test it now
--     journalctl --user -u app-openkraken@autostart.service      # and read it
--
-- Keep --minimized in the .desktop rather than setting start_minimized in
-- config.json, so launching by hand still opens the window normally.
--
-- Or, to keep startup alongside the rest of your Hyprland config, put this in
-- ~/.config/hypr/autostart.lua instead:
--
--     o.launch_on_start("openkraken --minimized")
--
-- No `sleep` is needed to wait for the bar. OpenKraken deliberately does not
-- probe QSystemTrayIcon.isSystemTrayAvailable() at startup (Qt caches that
-- answer once per process, so asking too early would poison it for the whole
-- session) — it creates the tray icon whenever the StatusNotifier watcher
-- shows up on the session bus, which on Omarchy is the Quickshell bar.
--
-- No sleep is needed to wait for the cooler, either: the engine retries the
-- connection every 5 s and re-applies curves, LCD and lighting once it lands,
-- so a cold boot that races udev's uaccess ACL heals itself.
